# Generated by Django 4.0.1 on 2022-03-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_galleryimages_imagelikes_bookreviews_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookreviews',
            name='book_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookreviews',
            name='review',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
