# Generated by Django 4.0.1 on 2022-03-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_articles_text_alter_articles_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='date_posted',
            field=models.DateField(auto_now=True),
        ),
    ]
