# Generated by Django 4.0.1 on 2022-03-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_galleryimages_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreviews',
            name='book_author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
